// Mocks generated by Mockito 5.4.6 from annotations
// in critter_app/test/view_model_unit_test/view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:critter_app/models/critter.dart' as _i5;
import 'package:critter_app/services/api_service.dart' as _i2;
import 'package:critter_app/storage/preferences_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get base => (super.noSuchMethod(
        Invocation.getter(#base),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#base),
        ),
      ) as String);

  @override
  _i4.Future<List<_i5.Critter>> fetchCritters(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCritters,
          [type],
        ),
        returnValue: _i4.Future<List<_i5.Critter>>.value(<_i5.Critter>[]),
      ) as _i4.Future<List<_i5.Critter>>);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i6.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> loadHemisphere() => (super.noSuchMethod(
        Invocation.method(
          #loadHemisphere,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #loadHemisphere,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> saveHemisphere(String? value) => (super.noSuchMethod(
        Invocation.method(
          #saveHemisphere,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
